### ISSUE TITLE
Problem caching reclustering

### ISSUE THREAD

**Issue by jlrestrepol** [michalk8/scachepy#13]
@michalk8 

Hi Mike,

when using the code below to cache the reclustering of my data(adata_rc is a restricted version of the adata object which contains Louvain clustering already) I'm getting that the routine is overwriting the 'louvain' feature instead of creating a new 'louvain_R' one and therefore ignoring the 'key_added' argument.

**When runnig this**

`c.tl.louvain(
             adata_rc, resolution=0.5, random_state=42, key_added ='louvain_R', 
             fname = 'reclustering', force = False
            )`

**I'm getting this:**

`Loading data from: "reclustering.pickle".`
`Warning: "adata.obs" already contains key: "'louvain'".`

My workaround is: 

`adata_rc.obs['louvain_aux'] = adata_rc.obs['louvain']`
`c.tl.louvain(adata_rc, resolution=0.5, random_state=42, key_added ='louvain_R', 
             fname = 'reclustering', force = False)`
`adata_rc.obs['louvain_R'] = adata_rc.obs['louvain']`
`adata_rc.obs['louvain'] = adata_rc.obs['louvain_aux']`
`del adata_rc.obs['louvain_aux']`

Is there a better way of doing that?

Thanks!

**Comment by michalk8** [comment]
Hey @jlrestrepol ,
unfortunately, there is no workaround when doing this, since I don't do the check where variables are being stored at runtime.
I wanted to implement this for a while and now it seems like a good time, will keep you updated.

**Comment by jlrestrepol** [comment]
Thanks a lot! 

Let me know if I can help in anyway.

**Comment by michalk8** [comment]
> Thanks a lot!
> 
> Let me know if I can help in anyway.

@jlrestrepol I've implemented it, currently just for `c.tl.louvain` and `c.tl.embedding_density`, could you please test it out? It's on `watchers` branch. In the meantime, I will deal with the rest of the functions.

**Comment by jlrestrepol** [comment]
@michalk8 Was planning to do it this morning but an OS update messed up my conda installation (among other things), I have a presentation tomorrow but after that I'll fix the problem and test your implementation out. 

Thanks and sorry for the inconveniences.

**Comment by jlrestrepol** [comment]
@michalk8  
I got an importation error because on line 402 of modules.py there is a repeated argument:

`watchers=dict(uns=['vkey'],
                                                       uns_cache1=['vkey'],
                                                       uns_cache1=['vkey']), `


Fixed the typo(?) and imported fine.

Also, I ran `c.tl.louvain(
             adata_rc, resolution=0.5, random_state=42, key_added='Louvain_R', fname = 'reclustering', force = False
            )` but I'm still getting the same behavior.

**Comment by michalk8** [comment]
Strange. Did you recache the object? Because I also cache where the keys were stored, so if previously the object was saved with `louvain`, then it will load it into `louvain`.
I don't do the runtime check on purpose, because it can lead to suble bugs - saving it as one key and loading as another. But it would seem this can lead to confusion. Do you think it would be better if loading also did the lookup?
If this fails after recaching with `Louvain_R` key, I will look more into it.

**Comment by jlrestrepol** [comment]
I ran it as you said and it worked fine. Thanks!

Question: I saw in your code you mainly look for the key 'key_added' what
would happen if I run the command with restrict_to=... That by default
creates Louvain_R but you don't need to add the key, is this a case that
should be also consider?

Regarding the run-time check, I think normally the right behavior is as you
have it and in some special cases, as loading a feature from a different
directory or just wanting not to overwrite a feature, having the ability to
set your own key would make sense. I think it can be useful if there's a
bug- free way to implement it, what do you think?

**Comment by michalk8** [comment]
> Question: I saw in your code you mainly look for the key 'key_added' what would happen if I run the command with restrict_to=... That by default creates Louvain_R but you don't need to add the key, is this a case that should be also consider?

I'm not sure what you mean. If `restrict_to` somehow modifies the name in `adata.obs` (I don't think it does), scachepy might find it, depending on previous keys in `adata.obs`.
As for the behavior, I will keep it like it is for now - if you cache it with `key_added='foo'`, it will load it always into `'foo'`, regardless whether you modify the call to be `key_added='bar'`.

It's now on master as well, unless you have any further question, then I'd close this.

**Comment by jlrestrepol** [comment]
`restrict_to` creates by default a new feature in `.obs` called "louvain_R" with the reclustering even if you don't specify a new key with `key_added`. I don't know if scachepy will in the case you call  the routine with `restrict_to`  and without `key_added` will overwrite the "Louvain" feature or will still create a new one called "louvain_R"

**Comment by michalk8** [comment]
Ah, I see. It didn't work, but I somewhat fixed it now, here's something to note:
```python
# will cache adata.obs['foo']
c.tl.louvain(adata, key_added='foo')

# will cache adata.obs['louvain_R']
c.tl.louvain(adata, fname='foo_R', 
             restrict_to=('paul15_clusters', ['7MEP']))

# will fail, you have to use keyhint='bar'
# it's because the key written is 'bar', not 'bar_R', as I would expect
c.tl.louvain(adata, key_added='bar', fname='bar_louvain2', 
             restrict_to=('paul15_clusters', ['7MEP']))
```

Do you think it would be beneficial to submit an issue to scanpy regarding the last point? To me, it's a minor, but still a valid issue, in terms of consistency.

**Comment by jlrestrepol** [comment]
Hmmm, I see what you mean. Well, I kinda agree with you, it's a minor but
still a value issue and it might be useful to at least mention it.

**Comment by michalk8** [comment]
Ok, I will think more about whether to create an issue, but since this feature seems to be working I am closing this via #14 .
