### ISSUE TITLE
Making this public

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#17]
Are there any steps we need to take before we can make this public? People start asking me whether they can use this.

**Comment by michalk8** [comment]
I've just added `dpt`, `leiden`, `combat`, `regress_out` and `scale`. I think . I haven't written tests for the newly added functions though (old tests still pass).
I think others can start using this, you haven't encountered any problems have you?

**Comment by michalk8** [comment]
Also be aware that `scvelo` has change a lot of things - the variables to keep. I've tried to keep the functions up to date but if something breaks down, let me know.

**Comment by Marius1311** [comment]
Great, thanks! I will open an issue on scanpy then to start discussing this.
