### ISSUE TITLE
pca is tl, not pp

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#23]
PCA is currently under pp, but in scanpy it's under tl, so I think we should stick to that.

**Comment by michalk8** [comment]
Based on the `scapy`'s docs, PCA is `pp` and `tl` alike. I can add it also under `tl`, but would keep it under `pp` as well. Here's the link: https://scanpy.readthedocs.io/en/stable/api/scanpy.pp.pca.html#scanpy.pp.pca

**Comment by Marius1311** [comment]
Oh - okay, I didn't know that. In that case, I take everything back and we can leave it where it is.
