### ISSUE TITLE
Adding TSNE

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#5]
I think tsne is fairly standard and especially since it takes longer to compute than UMAP, should be added to the default implemented caching functions.

**Comment by michalk8** [comment]
I believe it's there (the notebooks says so).

**Comment by Marius1311** [comment]
oh, maybe I was using an outdated version of scachepy.

**Comment by michalk8** [comment]
I checked it, it's there and working. Closing this.

**Comment by Marius1311** [comment]
Thanks Mike! I was in fact using an outdates version, my bad...
