### ISSUE TITLE
Cache fails when notebook is restarted

### ISSUE THREAD

**Issue by michalk8** [michalk8/scachepy#6]
After restarting the notebook, caching e.g. louvain does not work - the data is scrambled seemingly randomly.
Seems like an `adata` object is different everytime notebook is restarted, at least in terms of cell ordering. How could that be? If that's the case, metadata about the order will be necessary for caching. It still works if one is just rerunning the notebook (without restarting it), but upon restart, the data is scrambled.
@Marius1311 can you confirm that you experience the same issue?

**Comment by Marius1311** [comment]
What do you mean by restarting? Restarting the kernel?

**Comment by michalk8** [comment]
> What do you mean by restarting? Restarting the kernel?
Yes, that's what I meant. But I've found the bug, it was my mistake - I used a `set` of cells to filter them out and everytime I restarted the notebook, it changed the order of them - very cheeky mistake I must admit.
Everything works now, sorry for the panic, closing this.

**Comment by Marius1311** [comment]
I was 99 percent sure you were just panicing hahahahah
But still I think it's really good that you are so observant and fast-acting.
