### ISSUE TITLE
Should add `scv.tl.recover_dynamics`

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#7]
This is new in scvelo and is used to fit parameters for the "dynamical model". It's usually the most expensive operation executed by scvelo, so we should add a caching function for it. I thing it only adds to .var

**Comment by Marius1311** [comment]
The function adds quite a few keys to adata.var, so it's a bit inconvenient to have to specify the caching function manually.

**Comment by michalk8** [comment]
Resolved via #8
